#Copyright (c) 2015, Everbloom Soft Solution (pvt) ltd. (http://www.everbloom.lk) All Rights Reserved.

#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing, software
##distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.

#----------------------------------
# Until M1 We will create and delate the db
Drop database IF  EXISTS XpenzContainer;
#----------------------------------

#----------Create Database Start------------
CREATE DATABASE IF NOT EXISTS XpenzContainer;
USE XpenzContainer;
#----------Create Database End--__----------



CREATE TABLE IF NOT EXISTS EXPENSES_LIFE_CYCLE(
	EXPENSES_LIFE_CYCLE_ID INTEGER NOT NULL AUTO_INCREMENT,
    FIRST_APPROVAL_USER VARCHAR(50),
    FIRST_APPROVAL_ON DATE,
	FINACIAL_APPROVAL_USER VARCHAR(50),
    FINACIAL_APPROVAL_ON DATE,
    FINAL_APPROVAL_USER VARCHAR(50),
	FINAL_APPROVAL_ON DATE,
	LIFE_CYCLE_STATUS VARCHAR(50) DEFAULT 'CREATED',
    CONSTRAINT PK_EXPENSES_LIFE_CYCLE PRIMARY KEY(EXPENSES_LIFE_CYCLE_ID)
)ENGINE INNODB;



CREATE TABLE IF NOT EXISTS EXPENSE_RECORD(
	EXPENSE_RECORD_ID INTEGER NOT NULL AUTO_INCREMENT,
	EXPENSE_RECORD_USER_ID VARCHAR(50) NOT NULL,
	EXPENSES_LIFE_CYCLE_ID INTEGER NOT NULL,
	EXPENSE_RECORD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (EXPENSES_LIFE_CYCLE_ID) REFERENCES EXPENSES_LIFE_CYCLE(EXPENSES_LIFE_CYCLE_ID),
	CONSTRAINT PK_EXPENSE_RECORD PRIMARY KEY(EXPENSE_RECORD_ID, EXPENSE_RECORD_USER_ID, EXPENSES_LIFE_CYCLE_ID)
)ENGINE INNODB;


-- Refer to http://stackoverflow.com/questions/1636877/how-can-i-store-and-retrieve-images-from-a-mysql-database-using-php
CREATE TABLE IF NOT EXISTS EXPENSES_ITEM_RECEIPT (
	EXPENSES_ITEM_RECEIPT_ID  INTEGER NOT NULL AUTO_INCREMENT,
	EXPENSES_ITEM_RECEIPT_TYPE      VARCHAR(25) NOT NULL,
    EXPENSES_ITEM_RECEIPT_IMAGE   BLOB        NOT NULL,
	CONSTRAINT PK_EXPENSES_ITEM_RECEIPT PRIMARY KEY(EXPENSES_ITEM_RECEIPT_ID)
)ENGINE INNODB;


CREATE TABLE IF NOT EXISTS EXPENSES_ITEM(
    EXPENSES_ITEM_ID INTEGER NOT NULL AUTO_INCREMENT,
	EXPENSE_RECORD_ID INTEGER NOT NULL,
	EXPENSES_ITEM_DATE DATE NOT NULL,
	EXPENSES_ITEM_PROJECT_CODE VARCHAR(40) NOT NULL,
	EXPENSES_ITEM_DESCRIPTION VARCHAR(500) NOT NULL,
	EXPENSES_ITEM_EXPENSE_TYPES VARCHAR(20) NOT NULL,
    EXPENSES_ITEM_ENGAGEMENT VARCHAR(40),
	EXPENSES_ITEM_PAYMENT_METHOD VARCHAR(40) DEFAULT 'CASH',
	EXPENSES_ITEM_REMARKS VARCHAR(500),
	EXPENSES_ITEM_RECEIPT VARCHAR(10) DEFAULT 'FALSE',
	EXPENSES_ITEM_SPENT_TRANS_CURRENCY VARCHAR(10),		
	EXPENSES_ITEM_SPENT_CURRENCY_TAX INTEGER,
	EXPENSES_ITEM_SPENT_AMOUNT INTEGER,
	EXPENSES_ITEM_EXCHANGE_RATE INTEGER,		
	EXPENSES_ITEM_PREFERED_CURRENCY VARCHAR(10) ,
	EXPENSES_ITEM_Total INTEGER,		
	EXPENSES_ITEM_RECEIPT_ID INTEGER,
	FOREIGN KEY (EXPENSES_ITEM_RECEIPT_ID) REFERENCES EXPENSES_ITEM_RECEIPT(EXPENSES_ITEM_RECEIPT_ID),
	FOREIGN KEY (EXPENSE_RECORD_ID) REFERENCES EXPENSE_RECORD(EXPENSE_RECORD_ID),
    CONSTRAINT PK_EXPENSES_ITEM PRIMARY KEY(EXPENSES_ITEM_ID, EXPENSE_RECORD_ID)
)ENGINE INNODB;



